// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7A71ySUOU2_wXTQqobe0EmqBff5A3sks',
    appId: '1:842962092774:android:af68bb774ce3f2f3bff127',
    messagingSenderId: '842962092774',
    projectId: 'do-an-cau-long-2025-85931',
    storageBucket: 'do-an-cau-long-2025-85931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvXDJNGf4Ekop8Odo_7iP9TJYfth4oO0Q',
    appId: '1:842962092774:ios:be0c42969f1033d2bff127',
    messagingSenderId: '842962092774',
    projectId: 'do-an-cau-long-2025-85931',
    storageBucket: 'do-an-cau-long-2025-85931.firebasestorage.app',
    iosBundleId: 'com.example.doAnQuanLyCauLong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvXDJNGf4Ekop8Odo_7iP9TJYfth4oO0Q',
    appId: '1:842962092774:ios:be0c42969f1033d2bff127',
    messagingSenderId: '842962092774',
    projectId: 'do-an-cau-long-2025-85931',
    storageBucket: 'do-an-cau-long-2025-85931.firebasestorage.app',
    iosBundleId: 'com.example.doAnQuanLyCauLong',
  );
}
